### ISSUE TITLE
chat-sample: Error from participant: Language model 'copilot-gpt-3.5-turbo' errored, check cause for more details

### ISSUE THREAD

**Issue by inventor-singh** [microsoft/vscode-extension-samples#1003]
### Extension sample

chat-sample

### VS Code version

1.89.0-insider

### What went wrong?

The chat participant shows up when running the extension. However when prompted, gives the following error:

Error from participant: Language model 'copilot-gpt-3.5-turbo' errored, check cause for more details

In the debug console: following errors are shown:

[extension] Error on conversation request: TypeError: e.processResponseFromChatEndpoint is not a function
    at Fwe (/Users/T982719/.vscode-insiders/extensions/github.copilot-chat-0.15.2024041202/dist/extension.js:1099:5751)
    at Vg.fetchMany (/Users/T982719/.vscode-insiders/extensions/github.copilot-chat-0.15.2024041202/dist/extension.js:1099:10361)
    at L2.provideLanguageModelResponse2 (/Users/T982719/.vscode-insiders/extensions/github.copilot-chat-0.15.2024041202/dist/extension.js:980:1801)

**Comment by isidorn** [comment]
@inventor-singh I can not reproduce this issue. Are you on latest VS Code insiders and latest Copilot Chat Pre-release?
