### ISSUE TITLE
decorator-sample doesn't work on node v8.12.0, timeout not defined

### ISSUE THREAD

**Issue by diberry** [Microsoft/vscode-extension-samples#142]
Is there a minimum node version for this sample to run. The timeout code looks like it should work.

The exact error is: 

`
Activating extension 'vscode-samples.decorator-sample' failed: timeout is not defined.
extensionHostProcess.js:753
Activating extension `vscode-samples.decorator-sample` failed:  timeout is not defined
extensionHostProcess.js:344
Here is the error stack:  ReferenceError: timeout is not defined
extensionHostProcess.js:344
    at triggerUpdateDecorations (C:\Users\diberry\repos\vscode-extensions\vscode-extension-samples\decorator-sample\src\extension.ts:51:3)
    at activate (C:\Users\diberry\repos\vscode-extensions\vscode-extension-samples\decorator-sample\src\extension.ts:33:3)
    at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:759:329)
    at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:759:6)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:758:173
    at <anonymous>
`

code from extension.ts, line 51

`
	let timeout : NodeJS.Timer | null = null;
	function triggerUpdateDecorations() {
		if (timeout) {
			clearTimeout(timeout);
		}
		timeout = setTimeout(updateDecorations, 500);
	}
`

**Comment by diberry** [comment]
On Windows 10, VSCode 1.30.2 (system setup)

**Comment by diberry** [comment]
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by shooteram** [comment]
@diberry the line 49 needs to be inside the `triggerUpdateDecorations` function because the function is called before the timer is set.
