### ISSUE TITLE
Error Compiling lsp-sample

### ISSUE THREAD

**Issue by paulhocker** [Microsoft/vscode-extension-samples#39]
>npm run compile

produces this log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Development\\Libs\\nodejs\\node.exe',
1 verbose cli   'C:\\Development\\Libs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile:server' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'precompile:server', 'compile:server', 'postcompile:server' ]
5 info lifecycle lsp--sample@0.0.1~precompile:server: lsp--sample@0.0.1
6 info lifecycle lsp--sample@0.0.1~compile:server: lsp--sample@0.0.1
7 verbose lifecycle lsp--sample@0.0.1~compile:server: unsafe-perm in lifecycle true
8 verbose lifecycle lsp--sample@0.0.1~compile:server: PATH: C:\Development\Libs\nodejs\node_modules\npm\bin\node-gyp-bin;c:\Development\Workspace\VsCode\vscode-extension-samples\lsp-sample\node_modules\.bin;c:\Development\Workspace\Python\uModules\env\Scripts;c:\Development\Bin;C:\Development\Utils\ConEmu\ConEmuPack.161206\ConEmu\Scripts;C:\Development\Utils\ConEmu\ConEmuPack.161206;C:\Development\Utils\ConEmu\ConEmuPack.161206\ConEmu;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Development\Libs\Java\jre8\bin;C:\Development\Libs\NintendoDevInteface;C:\Program Files\Nintendo\HostBridge;C:\Development\Libs\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\paul\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft VS Code Insiders\bin;C:\Users\paul\AppData\Roaming\npm;;c:\Development\Libs;c:\Development\Libs\Java\jdk1.8\bin;C:\Program Files\Git\cmd;c:\Development\Tools\SQLite;C:\Program Files\Mercurial;C:\Games2\Emulators\Commodore\WinVice\WinVice-3.0.0;C:\Games2\Emulators\Atari\Stella\Stella-2.4.1;c:\Development\Tools\Pico\pico-8_0.1.4d_windows;c:\Development\Tools\Voxatron\voxatron_0.3.4_windows;C:\Games2\Emulators\Atari\z26\z26v3.02.01x;c:\Development\Utils\DoxyGen\1.8.11;c:\Development\Utils\SysInternalsSuite;c:\Development\Tools\6502\Assemblers\acme\acme-0.95;c:\Development\Tools\6502\Assemblers\dasm\dasm-2.20;c:\Development\Tools\6502\Assemblers\kickass\kickass-4.13;c:\Development\Tools\6502\Assemblers\turbo\64tass-1.51.992;;C:\Program Files\opencbm;C:\Games2\Emulators\Mame\Mame183;c:\Progra~1\7-ZIP;;c:\Development\Libs\Python\Python35;c:\Development\Libs\Python\Python35\Scripts;
9 verbose lifecycle lsp--sample@0.0.1~compile:server: CWD: c:\Development\Workspace\VsCode\vscode-extension-samples\lsp-sample
10 silly lifecycle lsp--sample@0.0.1~compile:server: Args: [ '/d /s /c',
10 silly lifecycle   'cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json' ]
11 silly lifecycle lsp--sample@0.0.1~compile:server: Returned: code: 2  signal: null
12 info lifecycle lsp--sample@0.0.1~compile:server: Failed to exec compile:server script
13 verbose stack Error: lsp--sample@0.0.1 compile:server: `cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Development\Libs\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Development\Libs\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid lsp--sample@0.0.1
15 verbose cwd c:\Development\Workspace\VsCode\vscode-extension-samples\lsp-sample
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Development\\Libs\\nodejs\\node.exe" "C:\\Development\\Libs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile:server"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error lsp--sample@0.0.1 compile:server: `cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json`
22 error Exit status 2
23 error Failed at the lsp--sample@0.0.1 compile:server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

also tried with node 7.9.0

**Comment by paulhocker** [comment]
I was able to get past this by removing node 8.9 and installing 7.9 - now I have a different error when trying to open the client. The task watch:client fails with the following:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Development\\Libs\\nodejs\\node.exe',
1 verbose cli   'C:\\Development\\Libs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch:client' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose config Skipping project config: C:\Users\paul/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\paul\package.json'
6 verbose cwd C:\Users\paul
7 error Windows_NT 10.0.15063
8 error argv "C:\\Development\\Libs\\nodejs\\node.exe" "C:\\Development\\Libs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch:client"
9 error node v7.9.0
10 error npm  v4.2.0
11 error path C:\Users\paul\package.json
12 error code ENOENT
13 error errno -4058
14 error syscall open
15 error enoent ENOENT: no such file or directory, open 'C:\Users\paul\package.json'
16 error enoent ENOENT: no such file or directory, open 'C:\Users\paul\package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -4058, true ]

So I "think" this has something to do with my environment setup on Windows, but cannot tell for sure. Why would it be looking for a package.json in my home directory?

**Comment by paulhocker** [comment]
Somehow I was able to get everything running again. I am a little disturbed because I am not exactly sure "how" I was able to get it running again. Needless to say, the changes I did make were

1. re-installed node 7.9
2. re-installed vscode 1.18.0 64-bit

short of that, I really wish I knew what fixed it

I will close this ticket

**Comment by paulhocker** [comment]
problem resolved . . . "somehow"
