### ISSUE TITLE
Error: Cannot find module 'lru-cache'

### ISSUE THREAD

**Issue by codeout** [microsoft/vscode-extension-samples#412]
I've developed [lsp-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample) based extension to find the client cannot load some modules.

```
# Log (Extension Host)

[2021-05-06 00:06:21.791] [exthost] [error] Activating extension codeout.vscode-junos failed due to an error:
[2021-05-06 00:06:21.792] [exthost] [error] Error: Cannot find module 'lru-cache'
```

<details>
<summary>Full error log</summary>

```
[2021-05-06 00:06:21.791] [exthost] [error] Activating extension codeout.vscode-junos failed due to an error:
[2021-05-06 00:06:21.792] [exthost] [error] Error: Cannot find module 'lru-cache'
Require stack:
- /Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/semver/classes/range.js
- /Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/semver/classes/comparator.js
- /Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/semver/index.js
- /Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/vscode-languageclient/lib/node/main.js
- /Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/vscode-languageclient/node.js
- /Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1019:15)
	at Module._load (internal/modules/cjs/loader.js:895:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
	at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/semver/classes/range.js:187:13)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
	at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/semver/classes/comparator.js:135:15)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
	at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/semver/index.js:34:15)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
	at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/vscode-languageclient/lib/node/main.js:21:16)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
	at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/node_modules/vscode-languageclient/node.js:7:18)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
	at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/Users/koji/.vscode/extensions/codeout.vscode-junos-0.2.0/client/out/extension.js:6:16)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)
	at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at require (internal/modules/cjs/helpers.js:72:18)
	at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at h._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:25918)
	at h._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:12016)
	at h._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:11072)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 0)
```

</details>

I'd think this is because `cd client; npm install` installs everything to `./client/node_modules` without `node_modules` nesting.

So probably we need:

### Option 1) Allowlist recursive dependencies in [.vscodeignore](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/.vscodeignore)

```diff
--- a/.vscodeignore
+++ b/.vscodeignore
@@ -11,7 +11,8 @@ client/node_modules/**
 !client/node_modules/vscode-languageclient/**
 !client/node_modules/vscode-languageserver-protocol/**
 !client/node_modules/vscode-languageserver-types/**
-!client/node_modules/semver/**
+!client/node_modules/{minimatch,brace-expansion,concat-map,balanced-match}/**
+!client/node_modules/{semver,lru-cache,yallist}/**
```

Cons: Difficult to track updates in 3rd party libralies.

### Option 2) Don't ignore `client/node_modules/**`

Cons: `.vsix` can be fat.

### Option 3) Bundle into a single file like webpack

Any suggestions on this?

**Comment by andrew-mclachlan** [comment]
Thank you for pointing out the problem! I modified my .vscodeignore accordingly and the extension worked!

**Comment by dbaeumer** [comment]
For now I would got with option one but the best is to webpack.

You can use https://github.com/microsoft/vscode-eslint/blob/main/shared.webpack.config.js#L1 as a blue print on how to webpack a LSP extension.
