### ISSUE TITLE
lsp-sample compilation error

### ISSUE THREAD

**Issue by Timmmm** [Microsoft/vscode-extension-samples#42]
I get this:

```
$ tsc -p client/tsconfig.json && cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json

> lsp-sample@0.0.1 installServer /Users/me/workspace/vscode-extension-samples/lsp-sample/server
> installServerIntoExtension ../client ./package.json ./tsconfig.json

Copying package.json to extension's server location...
Updating server npm modules into extension's server location...
server/src/server.ts(25,5): error TS6133: 'workspaceRoot' is declared but its value is never read.
```

**Comment by pascalpoizat** [comment]
Hello

same issue here.

```
npm run compile

> lsp--sample@0.0.1 compile /Users/pascalpoizat/Documents/Code/vscode-extension-samples/lsp-sample
> tsc -p client/tsconfig.json && cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json


> lsp-sample@0.0.1 installServer /Users/pascalpoizat/Documents/Code/vscode-extension-samples/lsp-sample/server
> installServerIntoExtension ../client ./package.json ./tsconfig.json

Copying package.json to extension's server location...
Updating server npm modules into extension's server location...
npm notice created a lockfile as package-lock.json. You should commit this file.
server/src/server.ts(25,5): error TS6133: 'workspaceRoot' is declared but its value is never read.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lsp--sample@0.0.1 compile: `tsc -p client/tsconfig.json && cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the lsp--sample@0.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pascalpoizat/.npm/_logs/2017-12-08T15_18_40_424Z-debug.log
```

**Comment by pascalpoizat** [comment]
The log for the issue mentioned above is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@5.6.0
3 info using node@v8.9.2
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle lsp--sample@0.0.1~precompile: lsp--sample@0.0.1
6 info lifecycle lsp--sample@0.0.1~compile: lsp--sample@0.0.1
7 verbose lifecycle lsp--sample@0.0.1~compile: unsafe-perm in lifecycle true
8 verbose lifecycle lsp--sample@0.0.1~compile: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pascalpoizat/Documents/Code/vscode-extension-samples/lsp-sample/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pascalpoizat/.local/bin
9 verbose lifecycle lsp--sample@0.0.1~compile: CWD: /Users/pascalpoizat/Documents/Code/vscode-extension-samples/lsp-sample
10 silly lifecycle lsp--sample@0.0.1~compile: Args: [ '-c',
10 silly lifecycle   'tsc -p client/tsconfig.json && cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json' ]
11 silly lifecycle lsp--sample@0.0.1~compile: Returned: code: 2  signal: null
12 info lifecycle lsp--sample@0.0.1~compile: Failed to exec compile script
13 verbose stack Error: lsp--sample@0.0.1 compile: `tsc -p client/tsconfig.json && cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid lsp--sample@0.0.1
15 verbose cwd /Users/pascalpoizat/Documents/Code/vscode-extension-samples/lsp-sample
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/Cellar/node/8.9.2/bin/node" "/usr/local/bin/npm" "run" "compile"
18 verbose node v8.9.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error lsp--sample@0.0.1 compile: `tsc -p client/tsconfig.json && cd server && npm run installServer && cd .. && tsc -p server/tsconfig.json`
22 error Exit status 2
23 error Failed at the lsp--sample@0.0.1 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by pascalpoizat** [comment]
Found a solution with https://github.com/Microsoft/vscode-extension-samples/issues/38
by applying what is proposed by @hessellund.
