### ISSUE TITLE
lsp-sample "module not found"

### ISSUE THREAD

**Issue by nadouamanda** [Microsoft/vscode-extension-samples#47]
I'm trying to run the example extension, but it seems like context.asAbsolutePath is returning an incorrect path for the server files. The absolute path is */vscode-extension-samples-master/lsp-sample/client/server/server.js' instead of */vscode-extension-samples-master/lsp-sample/server/server.js'.

module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/xxxx/Documents/vscode-extension-samples-master/lsp-sample/client/server/server.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (/Users/yuxinjiang/Documents/vscode-extension-samples-master/lsp-sample/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)

**Comment by dbaeumer** [comment]
This works for me. Please note that the server is compile into the client/server folder to make the client self contained. There are tasks (watch & compile) that do the right thing. You can then launch the client and the server is picked up correctly.

I will close the issue. Please ping if this is not addressing your problem.
