### ISSUE TITLE
lsp-embedded-request-forwarding: CSS completion not working - Error: Unable to resolve text model content for resource

### ISSUE THREAD

**Issue by discretegames** [microsoft/vscode-extension-samples#494]
When I run the request forwarding extension and edit the CSS in a .html1 file, no completions show up as promised. Nothing happens.

Instead I see this error output in my Log (Extension Host):

```text
[2021-09-22 18:30:00.779] [exthost] [error] Error: Unable to resolve text model content for resource embedded-content://css/file%3A///c%253A/Users/r/Tutorials/folder/h.html1.css
    at o.resolveTextModelContent (vscode-file://vscode-app/c:/Users/r/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2420:114062)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.doCreateReferencedObject (vscode-file://vscode-app/c:/Users/r/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2420:112900)
    at async i.acquire (vscode-file://vscode-app/c:/Users/r/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:17:14802)
    at async createModelReference (vscode-file://vscode-app/c:/Users/r/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2420:114749)
    at async vscode-file://vscode-app/c:/Users/r/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:677:16156 vscode.executeCompletionItemProvider
[2021-09-22 18:30:00.779] [exthost] [error] [vscode-samples.lsp-embedded-language-service-sample] provider FAILED
[2021-09-22 18:30:00.779] [exthost] [error] Error: Running the contributed command: 'vscode.executeCompletionItemProvider' failed.
    at _executeContributedCommand (c:\Users\r\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:111039)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.provideCompletionItem (c:\Users\r\Tutorials\lspfinaltest\vscode-extension-samples\lsp-embedded-request-forwarding\client\src\extension.ts:60:12)
    at $.provideCompletionItems (c:\Users\r\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:176917)
```

Triggered at [this line](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-embedded-request-forwarding/client/src/extension.ts#L60).

**Comment by van4elo** [comment]
@discretegames

**Comment by Vedthakar** [comment]
Hi I would look to try to solve this!
