### ISSUE TITLE
CustomTextEditor sample: Editor pane crashes for large files

### ISSUE THREAD

**Issue by phschaad** [microsoft/vscode-extension-samples#605]
## Steps to Reproduce:

1. Use the custom text editor sample extension (https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample).
2. Attempt to open a `.cscratch` file of ~100MB in size.

## Expected Behavior:
The file opens.

## Observed / Problematic Behavior: 
The editor pane briefly opens without showing content, showing that the extension is activating, before the pane vanishes again and the following error popup is displayed:

`Unable to open 'example2.cscratch': Assertion Failed: argument is undefined or null.` 

Debugging the extension reveals two things:

1. The crash happens _before_ the `CustomTextEditorProvider`'s `resolveCustomTextEditor` method is called.
2. The developer console shows the following error stack:

<details>
<summary>Error stack</summary>
Image form:

![image](https://user-images.githubusercontent.com/9193712/162197067-0d030fa1-122d-4b53-8409-bde128118c2c.png)

Textual form:
```
ERR Unable to retrieve document from URI 'file:///d%3A/UserData/Downloads/tmp/exampleFiles/example2.cscratch': Error: Unable to retrieve document from URI 'file:///d%3A/UserData/Downloads/tmp/exampleFiles/example2.cscratch'         (log.ts:313)
    at R.getDocument (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:71180)
    at _.$resolveWebviewEditor (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:82530)
    at i._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12119)
    at i._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)


ERR Error: Assertion Failed: argument is undefined or null                                               (log.ts:313)
    at i (types.ts:119:9)
    at Cn.resolve (customEditorInput.ts:303:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Go.setInput (webviewEditor.ts:137:3)
    at async i.doSetInput (editorPanes.ts:281:4)
    at async i.doOpenEditor (editorPanes.ts:150:34)
    at async i.openEditor (editorPanes.ts:118:11)
    at async editorGroupView.ts:1096:49
    at async Mi.openEditors (editorGroupView.ts:1237:3)
    at async Promise.all (index 0)
    at async Object.X [as settled] (async.ts:1450:18)
    at async O.openEditors (editorService.ts:604:19)

Unable to open 'example2.cscratch': Assertion Failed: argument is undefined or null.      (notificationsAlerts.ts:42)
```
</details>

I can provide the exact example file if desired, but have omitted it due to the size.

## Environment:
- VS Code Version: 1.66.0, Electron 17.2.0 - Extension API Version 1.55.0, also tested on 1.52.0
- OS Version: Windows 10, Build 19044.1586

**Comment by mjbvz** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/147000 (although may move back as it may just be an extension sample code issue)
