### ISSUE TITLE
Bug/Typo in JS file: "/product-icon-theme-sample/build/updateFont.js" @Line #33

### ISSUE THREAD

**Issue by JAYD3V** [microsoft/vscode-extension-samples#650]
### Problem:

https://github.com/microsoft/vscode-extension-samples/blob/039da585afdb164282ea9a8d1f73dae4f9912319/product-icon-theme-sample/build/updateFont.js#L32-L34

### Solution:

```
32  } catch (e) {
33      console.error('Font creation failed.', e);
34  }
```

<br>

Below is the output from an instance of the program in which the erroneous line was executed.

To get **line-33** to execute, I assigned an erroneous file location to the `dest` variable **_[@ Line 29](https://github.com/microsoft/vscode-extension-samples/blob/039da585afdb164282ea9a8d1f73dae4f9912319/product-icon-theme-sample/build/updateFont.js#L29)_**.

##### OUTPUT:

```
> node ./build/updateFont.js

Font created
/home/jayd3v/Development/Projects/VSCode-Extensions/Azurite/build/updateFont.js:35
    console.error('Font creation failed.', error);
                                           ^

ReferenceError: error is not defined
    at generateFont (/home/jayd3v/Development/Projects/VSCode-Extensions/Azurite/build/updateFont.js:35:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.2.0

```

**Comment by JAYD3V** [comment]
> ### Problem:
> 
> https://github.com/microsoft/vscode-extension-samples/blob/039da585afdb164282ea9a8d1f73dae4f9912319/product-icon-theme-sample/build/updateFont.js#L32-L34
> 
> ### Solution:
> 
> ```
> 32  } catch (e) {
> 33      console.error('Font creation failed.', e);
> 34  }
> ```
> 
> 
> Below is the output from an instance of the program in which the erroneous line was executed.
> 
> To get **line-33** to execute, I assigned an erroneous file location to the `dest` variable **_[@ Line 29](https://github.com/microsoft/vscode-extension-samples/blob/039da585afdb164282ea9a8d1f73dae4f9912319/product-icon-theme-sample/build/updateFont.js#L29)_**.
> ##### OUTPUT:
> 
> ```
> > node ./build/updateFont.js
> 
> Font created
> /home/jayd3v/Development/Projects/VSCode-Extensions/Azurite/build/updateFont.js:35
>     console.error('Font creation failed.', error);
>                                            ^
> 
> ReferenceError: error is not defined
>     at generateFont (/home/jayd3v/Development/Projects/VSCode-Extensions/Azurite/build/updateFont.js:35:44)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.2.0
> ```

I'd happily fix it, but I couldn't figure out how to make a pull request, or push a commit, for a bug that there was no issue previously created for. If there is a better way I could have helped, tell me what it is, and that's what I will do in the future. I have been spending much time in VS Code's repositories lately.
