### ISSUE TITLE
"Mocha is not defined" error when running tests

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-extension-samples#651]
We made a fork of the lsp-sample repo and made some changes to the server to add our own diagnostics. Then we modified the diagnostics test accordingly and getting this error when running `npm run test`. I can see the extension host window comes up, but no document gets opened and it just ends with this error.

I can see the `mocha` in dev dependencies in the root package.json. Is there something we're missing?

```
Found existing install in /Users/gvalenc/git/Nick-Steinhauser/vscode-lsp-fork/.vscode-test/vscode-darwin-1.67.2. Skipping download
[main 2022-05-25T20:54:08.964Z] window#load: attempt to load window (id: 1)
[main 2022-05-25T20:54:09.220Z] update#ctor - updates are disabled by the environment
[main 2022-05-25T20:54:09.979Z] ExtensionHostStarterWorker created
2022-05-25 15:54:11.381 Code Helper (Renderer)[43822:10012431] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2022-05-25 15:54:11.381 Code Helper (Renderer)[43822:10012431] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
[main 2022-05-25T20:54:11.563Z] window#load: window reported ready (id: 1)
Loading development extension at /Users/gvalenc/git/Nick-Steinhauser/vscode-lsp-fork
[main 2022-05-25T20:54:17.848Z] Starting extension host with pid 44622 (fork() took 8 ms).
[main 2022-05-25T20:54:17.863Z] ExtensionHostStarterWorker.start() took 25 ms.
[main 2022-05-25T20:54:19.053Z] Extension host with pid 44622 exited with code: 1, signal: null.
ReferenceError: Mocha is not defined
	at Object.run (/Users/gvalenc/git/Nick-Steinhauser/vscode-lsp-fork/client/out/test/index.js:34:19)
	at /Users/gvalenc/git/Nick-Steinhauser/vscode-lsp-fork/.vscode-test/vscode-darwin-1.67.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:20035
	at new Promise (<anonymous>)
	at m._doHandleExtensionTests (/Users/gvalenc/git/Nick-Steinhauser/vscode-lsp-fork/.vscode-test/vscode-darwin-1.67.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:19919)
	at async m.$extensionTestsExecute (/Users/gvalenc/git/Nick-Steinhauser/vscode-lsp-fork/.vscode-test/vscode-darwin-1.67.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:19489)
Exit code:   1
Failed to run tests
```

**Comment by gee4vee** [comment]
This is the client's tsconfig.json:

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
    "esModuleInterop": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "out",
    "rootDir": "src",
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "forceConsistentCasingInFileNames": true,
    "target": "esnext",
    "module": "CommonJS",
    "moduleResolution": "node",
    "types": ["node", "vscode"]
  },
  "include": ["src"],
  "exclude": ["node_modules", ".vscode-test"]
}
```

**Comment by dbaeumer** [comment]
@gee4vee actually that depends on the changes you did. The tests run for me without problem when cloning the repository. 

Do they run for you when you clone the repository?

**Comment by gee4vee** [comment]
@dbaeumer yes they do. Could it be because of our tsc config changes? I can see in the compiled index.js that there is no import of `mocha`.

**Comment by gee4vee** [comment]
In the cloned repository, I can see the compiled code gets:

`const Mocha = require("mocha");`

So it probably is related to my tsc config settings and/or the code.

**Comment by gee4vee** [comment]
Got it to work by using this style of import:

`import Mocha from "mocha";`

Thanks for looking at this anyway.
