### ISSUE TITLE
i18n sample package error

### ISSUE THREAD

**Issue by RiuHDuo** [microsoft/vscode-extension-samples#725]
i run command `gulp pakcage` and get an error;

```shell
[10:38:54] Using gulpfile ~\Downloads\i18n-sample\gulpfile.js
[10:38:54] Starting 'package'...
[10:38:54] Starting 'cleanTask'...
[10:38:54] Finished 'cleanTask' after 8.62 ms
[10:38:54] Starting 'internalNlsCompileTask'...
[10:38:55] 'internalNlsCompileTask' errored after 1.3 s
[10:38:55] TypeError: host.fileExists is not a function
    at Object.fileExists (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:167620:63)
    at Object.host.fileExists (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:117500:47)
    at getPackageJsonInfo (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:44461:37)
    at loadModuleFromSpecificNodeModulesDirectory (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:45001:27)
    at loadModuleFromImmediateNodeModulesDirectory (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:44982:58)
    at C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:44972:39
    at Object.forEachAncestorDirectory (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:8370:26)
    at loadModuleFromNearestNodeModulesDirectoryWorker (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:44966:19)
    at loadModuleFromNearestNodeModulesDirectory (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:44958:16)
    at tryResolve (C:\Users\fearm\Downloads\i18n-sample\node_modules\typescript\lib\typescript.js:44053:34)
[10:38:55] 'package' errored after 1.32 s
```
![image](https://user-images.githubusercontent.com/830134/195238218-3fc56c72-e127-44d7-aec4-21aae25ac2f7.png)

**Comment by RiuHDuo** [comment]
upgrade vscode-nls-dev to 4.0.3 and fix this error

**Comment by KamasamaK** [comment]
That sample is being replaced soon anyway. See #721.
