### ISSUE TITLE
lsp-sample compile fails again

### ISSUE THREAD

**Issue by burner1024** [microsoft/vscode-extension-samples#90]
```
$ npm run compile
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle lsp-sample@1.0.0~precompile: lsp-sample@1.0.0
6 silly lifecycle lsp-sample@1.0.0~precompile: no script for precompile, continuing
7 info lifecycle lsp-sample@1.0.0~compile: lsp-sample@1.0.0
8 verbose lifecycle lsp-sample@1.0.0~compile: unsafe-perm in lifecycle true
9 verbose lifecycle lsp-sample@1.0.0~compile: PATH: /usr/share/npm/bin/node-gyp-bin:/home/usr/test/vscode-extension-samples/lsp-sample/node_modules/.bin:/home/usr/.npm-global/bin:/home/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/usr/.local/bin:/home/usr/.gem/ruby/2.5.0/bin
10 verbose lifecycle lsp-sample@1.0.0~compile: CWD: /home/usr/test/vscode-extension-samples/lsp-sample
11 silly lifecycle lsp-sample@1.0.0~compile: Args: [ '-c', 'npm run compile:client && npm run compile:server' ]
12 silly lifecycle lsp-sample@1.0.0~compile: Returned: code: 1  signal: null
13 info lifecycle lsp-sample@1.0.0~compile: Failed to exec compile script
14 verbose stack Error: lsp-sample@1.0.0 compile: `npm run compile:client && npm run compile:server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid lsp-sample@1.0.0
16 verbose cwd /home/usr/test/vscode-extension-samples/lsp-sample
17 error Linux 4.15.0-33-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error lsp-sample@1.0.0 compile: `npm run compile:client && npm run compile:server`
22 error Exit status 1
23 error Failed at the lsp-sample@1.0.0 compile script 'npm run compile:client && npm run compile:server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the lsp-sample package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run compile:client && npm run compile:server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs lsp-sample
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls lsp-sample
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dbaeumer** [comment]
This works for me without problems. Anything you can think of that makes it special for you:

<img width="1042" alt="capture" src="https://user-images.githubusercontent.com/1931590/44875017-3b53f100-ac9d-11e8-811f-6462dfe0f270.png">

**Comment by burner1024** [comment]
well... Ubuntu?
Also, adding some log I missed:
```
tsc -p ./client/tsconfig.json

client/node_modules/vscode-languageclient/lib/client.d.ts(1,707): error TS2305: Module ''vscode'' has no exported member 'DocumentSymbol'.
client/node_modules/vscode-languageclient/lib/protocolConverter.d.ts(54,54): error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.
client/node_modules/vscode-languageclient/lib/protocolConverter.d.ts(56,57): error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.
client/node_modules/vscode-languageclient/lib/protocolConverter.d.ts(57,76): error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.
```

**Comment by dbaeumer** [comment]
I think you need to run `npm run update-vscode`. The reason is that you have an outdated vscode.d.ts file on disk. I will think about how to automate this. Not easy since we don't want to do this on every compile :-)

**Comment by burner1024** [comment]
Still not working:
```
lsp-sample/client$ npm run update-vscode

> lsp-sample-client@0.0.1 update-vscode /tmp/vscode-extension-samples/lsp-sample/client
> vscode-install

Detected VS Code engine version: ^1.23.0
Found minimal version that qualifies engine range: 1.23.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

lsp-sample/client$ cd ..
lsp-sample$ tsc -p ./client/tsconfig.json
client/node_modules/vscode-languageclient/lib/client.d.ts:1:707 - error TS2305: Module ''vscode'' has no exported member 'DocumentSymbol'.
```

**Comment by dbaeumer** [comment]
This works for me without problems. Did you change the version number of the `vscode-languageclient` ?

**Comment by burner1024** [comment]
No... I literally do ctrl-c/ctrl-v from the [docs](https://code.visualstudio.com/docs/extensions/example-language-server). Fresh clone, no manual changes.

**Comment by dbaeumer** [comment]
Interestingly I was able to reproduce after deleting the `package-lock.json`.

**Comment by dbaeumer** [comment]
I will version lock the version in the npm modules itself. I have no idea why this is not respected for you with the lock file. Do you use some other module manager?

**Comment by dbaeumer** [comment]
I will make sure that with the next vscode-* version I will version lock these dependencies inside the package.json

**Comment by burner1024** [comment]
No, it's just Ubuntu 18.04, npm from universe. Tried on another machine with the same OS, fails with the same error.
Maybe some automatic tests would be helpful here.

**Comment by mjbvz** [comment]
Closing as out of date and no other users have reported the issue

**Comment by jmarolf** [comment]
can confirm cloning and following directions in this repo results in this issue.

**Comment by burner1024** [comment]
the same issue keeps popping up for the last 2 years, I say that calls for some autotests.

**Comment by dbaeumer** [comment]
I just clones the repositor and cd into lsp-sample and ran:

```sh
> npm install
> npm run compile
````

and it worked without any problems. If you still see issues, can you please provide the steps you are executing

**Comment by burner1024** [comment]
These are the [steps](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#implementing-a-language-server):

> Clone the repository Microsoft/vscode-extension-samples and open the sample:
> 
```
git clone https://github.com/Microsoft/vscode-extension-samples.git
cd vscode-extension-samples/lsp-sample
npm install
npm run compile
code .
```

**Comment by jmarolf** [comment]
perhaps there is a problem with a particular version of npm or something else in my environment? I will try and capture what info I can when I get back to my machine. What info typically helps in diagnosing this problem?  As @burner1024 	says just following the directions results in a version of the vscode package that does not compile.

**Comment by dbaeumer** [comment]
@burner1024 these are the exact same steps I do. So there must be a difference in the environment.

Here is the npm and node version I use:

```
node: v10.15.1
npm: 6.4.1
```

**Comment by burner1024** [comment]
I got node v8.10.0, npm 3.5.2 - default on latest Ubuntu LTS.

**Comment by dbaeumer** [comment]
Not sure if it makes a difference but in general it is best to match VS Code's node version (which is currently 10.11.0) when doing plugin development.

**Comment by burner1024** [comment]
Well, maybe add that to the docs? Print a warning, or something else?
I mean, the very first textbook example fails, that's kind of discouraging.

**Comment by jmarolf** [comment]
@dbaeumer 	that is likely it. I am also on node 8

**Comment by dbaeumer** [comment]
Done.

**Comment by igorlopez** [comment]
I know this issue was closed in end of May but I have the same problem due to other issues and instead of creating a new issue we will see if we can sort out the problem (on my side most likely) here.
This is when running on Ubuntu 16.04 with:

> node: v12.7.0
> npm: 6.10.0

The repo was cloned about a week ago,

```
<DEV>/vscode-extension-samples$ git log
commit e5418aced1346b2bfcbf3ef74045c6f0f4b2b733
Author: Daniel Imms <daimms@microsoft.com>
Date:   Fri Aug 2 14:56:52 2019 -0700

    Add extension terminal sample
```

And no changes done, e.g. this is the status after a failed compile:

```
<DEV>/Development/vscode-extension-samples$ git status
På grenen master
Din gren är à jour med "origin/master".
Ändringar ej i incheckningskön:
  (använd "git add <fil>..." för att uppdatera vad som skall checkas in)
  (använd "git checkout -- <fil>..." för att förkasta ändringar i arbetskatalogen)

	ändrad:        i18n-sample/package-lock.json
	ändrad:        lsp-sample/client/package-lock.json
	ändrad:        lsp-sample/package-lock.json

Ospårade filer:
  (använd "git add <fil>..." för att ta med i det som skall checkas in)

	package-lock.json

inga ändringar att checka in (använd "git add" och/eller "git commit -a")
```

Sorry for the output being in Swedish but I guess one can understand the output anyway.

The install went as expected:

```
<DEV>/Development/vscode-extension-samples$ npm install

> vsc-extension-samples@0.0.1 install <USER-HOME>/Development/vscode-extension-samples
> node .scripts/run-install.js
....
up to date in 82.957s
found 0 vulnerabilities
```

But the compile failed:

```
<DEV>/vscode-extension-samples$ npm run compile

> vsc-extension-samples@0.0.1 compile <DEV>/vscode-extension-samples
> node .scripts/run-script.js compile

=== Running compile on webview-sample ===

> cat-coding@0.0.1 compile <DEV>/vscode-extension-samples/webview-sample
> tsc -p ./

=== Running compile on statusbar-sample ===

> status-ts@0.0.1 compile <DEV>/vscode-extension-samples/statusbar-sample
> tsc -p ./

=== Running compile on tree-view-sample ===

> custom-view-samples@0.0.1 compile <DEV>/vscode-extension-samples/tree-view-sample
> tsc -p ./

=== Running compile on task-provider-sample ===

> task-provider-samples@0.0.1 compile <DEV>/vscode-extension-samples/task-provider-sample
> tsc -b

=== Running compile on basic-multi-root-sample ===

> basic-multi-root-sample@0.0.1 compile <DEV>/vscode-extension-samples/basic-multi-root-sample
> tsc -p ./

=== Running compile on completions-sample ===

> completions-sample@0.0.2 compile <DEV>/vscode-extension-samples/completions-sample
> tsc -p ./

=== Running compile on code-actions-sample ===

> code-actions-sample@0.0.2 compile <DEV>/vscode-extension-samples/code-actions-sample
> tsc -p ./

=== Running compile on fsprovider-sample ===

> vscode-memfs@0.0.3 compile <DEV>/vscode-extension-samples/fsprovider-sample
> tsc -p ./

=== Running compile on decorator-sample ===

> decorator-sample@0.0.1 compile <DEV>/vscode-extension-samples/decorator-sample
> tsc -p ./

=== Running compile on i18n-sample ===

> i18n-sample@0.1.0 compile <DEV>/vscode-extension-samples/i18n-sample
> tsc -b

=== Running compile on terminal-sample ===

> vscode-terminal-api-example@0.0.1 compile <DEV>/vscode-extension-samples/terminal-sample
> tsc -p ./

=== Running compile on vim-sample ===

> vim@0.0.1 compile <DEV>/vscode-extension-samples/vim-sample
> tsc -p ./

=== Running compile on source-control-sample ===

> source-control-sample@0.0.1 compile <DEV>/vscode-extension-samples/source-control-sample
> tsc -p ./

=== Running compile on comment-sample ===

> vscode-comment-api-example@0.0.1 compile <DEV>/vscode-extension-samples/comment-sample
> tsc -p ./

src/extension.ts:7:7 - error TS2559: Type 'NoteComment' has no properties in common with type 'Comment'.

7 class NoteComment implements vscode.Comment {
        ~~~~~~~~~~~

src/extension.ts:12:23 - error TS2694: Namespace '"vscode"' has no exported member 'CommentMode'.

12  	public mode: vscode.CommentMode,
    	                    ~~~~~~~~~~~

src/extension.ts:13:25 - error TS2694: Namespace '"vscode"' has no exported member 'CommentAuthorInformation'.

13  	public author: vscode.CommentAuthorInformation,
    	                      ~~~~~~~~~~~~~~~~~~~~~~~~

src/extension.ts:14:26 - error TS2694: Namespace '"vscode"' has no exported member 'CommentThread'.

14  	public parent?: vscode.CommentThread
    	                       ~~~~~~~~~~~~~

src/extension.ts:22:35 - error TS2339: Property 'comments' does not exist on type 'typeof import("vscode")'.

22  const commentController = vscode.comments.createCommentController('comment-sample', 'Comment API Sample');
                                     ~~~~~~~~

src/extension.ts:34:97 - error TS2694: Namespace '"vscode"' has no exported member 'CommentReply'.

34  context.subscriptions.push(vscode.commands.registerCommand('mywiki.createNote', (reply: vscode.CommentReply) => {
                                                                                                   ~~~~~~~~~~~~

src/extension.ts:38:96 - error TS2694: Namespace '"vscode"' has no exported member 'CommentReply'.

38  context.subscriptions.push(vscode.commands.registerCommand('mywiki.replyNote', (reply: vscode.CommentReply) => {
                                                                                                  ~~~~~~~~~~~~

src/extension.ts:42:97 - error TS2694: Namespace '"vscode"' has no exported member 'CommentReply'.

42  context.subscriptions.push(vscode.commands.registerCommand('mywiki.startDraft', (reply: vscode.CommentReply) => {
                                                                                                   ~~~~~~~~~~~~

src/extension.ts:45:55 - error TS2339: Property 'CommentMode' does not exist on type 'typeof import("vscode")'.

45  	let newComment = new NoteComment(reply.text, vscode.CommentMode.Preview, { name: 'vscode' }, thread);
    	                                                    ~~~~~~~~~~~

src/extension.ts:50:98 - error TS2694: Namespace '"vscode"' has no exported member 'CommentReply'.

50  context.subscriptions.push(vscode.commands.registerCommand('mywiki.finishDraft', (reply: vscode.CommentReply) => {
                                                                                                    ~~~~~~~~~~~~

src/extension.ts:59:36 - error TS2339: Property 'CommentThreadCollapsibleState' does not exist on type 'typeof import("vscode")'.

59  	thread.collapsibleState = vscode.CommentThreadCollapsibleState.Collapsed;
    	                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/extension.ts:60:55 - error TS2339: Property 'CommentMode' does not exist on type 'typeof import("vscode")'.

60  	let newComment = new NoteComment(reply.text, vscode.CommentMode.Preview, { name: 'vscode' }, thread);
    	                                                    ~~~~~~~~~~~

src/extension.ts:73:44 - error TS7006: Parameter 'cmt' implicitly has an 'any' type.

73  	thread.comments = thread.comments.filter(cmt => (cmt as NoteComment).id !== comment.id);
    	                                         ~~~

src/extension.ts:80:98 - error TS2694: Namespace '"vscode"' has no exported member 'CommentThread'.

80  context.subscriptions.push(vscode.commands.registerCommand('mywiki.deleteNote', (thread: vscode.CommentThread) => {
                                                                                                    ~~~~~~~~~~~~~

src/extension.ts:89:57 - error TS7006: Parameter 'cmt' implicitly has an 'any' type.

89  	comment.parent.comments = comment.parent.comments.map(cmt => {
    	                                                      ~~~

src/extension.ts:91:23 - error TS2339: Property 'CommentMode' does not exist on type 'typeof import("vscode")'.

91  			cmt.mode = vscode.CommentMode.Preview;
    			                  ~~~~~~~~~~~

src/extension.ts:103:57 - error TS7006: Parameter 'cmt' implicitly has an 'any' type.

103  	comment.parent.comments = comment.parent.comments.map(cmt => {
     	                                                      ~~~

src/extension.ts:105:23 - error TS2339: Property 'CommentMode' does not exist on type 'typeof import("vscode")'.

105  			cmt.mode = vscode.CommentMode.Preview;
     			                  ~~~~~~~~~~~

src/extension.ts:117:57 - error TS7006: Parameter 'cmt' implicitly has an 'any' type.

117  	comment.parent.comments = comment.parent.comments.map(cmt => {
     	                                                      ~~~

src/extension.ts:119:23 - error TS2339: Property 'CommentMode' does not exist on type 'typeof import("vscode")'.

119  			cmt.mode = vscode.CommentMode.Editing;
     			                  ~~~~~~~~~~~

src/extension.ts:130:35 - error TS2694: Namespace '"vscode"' has no exported member 'CommentReply'.

130  function replyNote(reply: vscode.CommentReply) {
                                      ~~~~~~~~~~~~

src/extension.ts:132:55 - error TS2339: Property 'CommentMode' does not exist on type 'typeof import("vscode")'.

132  	let newComment = new NoteComment(reply.text, vscode.CommentMode.Preview, { name: 'vscode' }, thread);
     	                                                    ~~~~~~~~~~~


Found 22 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-comment-api-example@0.0.1 compile: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-comment-api-example@0.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <USER-HOME>/.npm/_logs/2019-08-15T11_41_49_223Z-debug.log
=== Running compile on document-editing-sample ===

> reverseword@0.0.1 compile <DEV>/vscode-extension-samples/document-editing-sample
> tsc -p ./

=== Running compile on lsp-sample ===

> lsp-sample@1.0.0 compile <DEV>/vscode-extension-samples/lsp-sample
> tsc -b

=== Running compile on lsp-log-streaming-sample ===

> lsp-log-streaming-sample@1.0.0 compile <DEV>/vscode-extension-samples/lsp-log-streaming-sample
> npm run compile:client && npm run compile:server


> lsp-log-streaming-sample@1.0.0 compile:client <DEV>/vscode-extension-samples/lsp-log-streaming-sample
> tsc -p ./client/tsconfig.json


> lsp-log-streaming-sample@1.0.0 compile:server <DEV>/vscode-extension-samples/lsp-log-streaming-sample
> tsc -p ./server/tsconfig.json

=== Running compile on lsp-multi-server-sample ===

> lsp-sample-multi-server@1.0.0 compile <DEV>/vscode-extension-samples/lsp-multi-server-sample
> tsc -b

(node:14742) UnhandledPromiseRejectionWarning: Error: Command failed: npm run compile
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at tryRun (<DEV>/vscode-extension-samples/.scripts/run-script.js:18:19)
    at Object.<anonymous> (<DEV>/vscode-extension-samples/.scripts/run-script.js:27:3)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
(node:14742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas?

**Comment by dbaeumer** [comment]
It works for me without problems.

What happens if you run `npm run compile` inside `lsp-multi-server-sample`. Since the `lsp-multi-server-sample` is the last sample that is being compiled it must not necessary be the source of the problem.

**Comment by igorlopez** [comment]
Hmm, seems to be a dependency problem since when doing the _npm run compile_ in the original folder the output is:

```
> lsp-sample@1.0.0 compile <DEV>/vscode-extension-samples/lsp-sample
> tsc -b
```
 
What I did was move the lsp-sample folder  outside of the vscode-extension-samples since my plan is to make a language server for assembler code to a programmable ASIC.

Since this whole vscode extension concept is totally new to me I have no knowledge of how to track dependencies and also knowing what files in the examples are the ones to actually maintain, e.g. what is the actual source, e.g. I see a lot of files in the node_modules folder that have almost the same names except for one is a <NAME>.d.ts file and the other is a <NAME>.js file.

So thanks for the help, I need to dig more to understand how thing works together.

**Comment by rfpg1** [comment]
I got the same error today when following the tutorial

```
npm run compile

lsp-sample@1.0.0 compile
tsc -b

/home/ricardo/Documents/Faculdade/Mestrado/TC/vscode-extension-samples/lsp-sample/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ricardo/Documents/Faculdade/Mestrado/TC/vscode-extension-samples/lsp-sample/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

All I did was 
```
git clone https://github.com/microsoft/vscode-extension-samples.git
cd vscode-extension-samples/lsp-sample
npm install
npm run compile
code .
```

If someone could help me

**Comment by rfpg1** [comment]
Managed to fix it by upgrading node version, I install version 18.16.0 but I believe it is required minimum 15
